global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: '/api/actuator/prometheus'
    metric_relabel_configs:
      - source_labels: [uri]
        regex: '/api/actuator.*'
        action: drop
    static_configs:
      - targets: ['localhost:80']